version: '3.7'
services:
  gateway-service-dev:
    container_name: gateway-service-dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      RUNNING_ENV: 'prod'
    networks:
      - redis-network
networks:
  redis-network:
    external:
      name: redis
