TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3211cf3a9f8d00e
  FEISHU_APP_SECRET: lQlKQMQz6XxJ1u0tzVTfJgC8F2P7MCEY
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
