TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3211cf3a9f8d00e
  FEISHU_APP_SECRET: lQlKQMQz6XxJ1u0tzVTfJgC8F2P7MCEY
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: 'runoob' # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: 'mongodb://admin:123456@localhost:27017' # 数据库链接地址
  username: 'admin' # 数据库链接用户名
  password: '123456' # 数据库链接密码
  database: 'admin' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
