TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3211cf3a9f8d00e
  FEISHU_APP_SECRET: lQlKQMQz6XxJ1u0tzVTfJgC8F2P7MCEY
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: 'runoob' # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: 'mongodb://admin:123456@host.docker.internal:27017' # 数据库链接地址
  username: 'admin' # 数据库链接用户名
  password: '123456' # 数据库链接密码
  database: 'admin' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: 'user-test'
  type: 'mysql'
  host: 'host.docker.internal'
  port: 3306
  username: 'root'
  password: '123456'
  database: 'USER_TEST'
  entities: 'mysql' # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true
REDIS_CONFIG:
  host: 'host.docker.internal' # redis连接
  port: 6379 # redis 端口
  auth: '' # redis 连接密码
  db: 1 # redis 数据库
USER_MICROSERVICES:
  host: '0.0.0.0'
  port: 4100
